apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-frontend-pod
  {{- .Values.network.frontend | toYaml | nindent 2 }}
