apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.db.mysqlRootPassword | b64enc }}
  MYSQL_USER: {{ .Values.secret.common.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secret.common.mysqlPassword | b64enc }}
