# Compose file for local development and testing. Images are built from
# local directories which need to be cloned from the repository. This uses
# self-signed TLS certificates 'ACME'.
version: '3.7'

services:

  traefik:
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:4433"

      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=postmaster@mydomain.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "4433:443"
    volumes:
      - "./letsencrypt:/letsencrypt"

  testcenter-backend:
    image: iqbberlin/testcenter-backend:11.5.1
    volumes:
      - testcenter_backend_vo_data:/var/www/html/vo_data
    labels:
      - "traefik.http.routers.testcenter-backend.tls=true"

  testcenter-frontend:
    image: iqbberlin/testcenter-frontend:8.1.0
    labels:
      - "traefik.http.routers.testcenter-frontend.tls=true"

  testcenter-broadcasting-service:
    image: iqbberlin/testcenter-broadcasting-service:4.0.0
    labels:
      - "traefik.http.routers.testcenter-broadcasting-service.tls=true"

volumes:
  testcenter_backend_vo_data:
