# Common 'Security Headers'
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: tc
spec:
  headers:
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    #stsPreload: true
    #forceSTSHeader: true
    customFrameOptionsValue: SAMEORIGIN
    contentTypeNosniff: true
    #browserXssFilter: true
    referrerPolicy: no-referrer
---

# Common HTTPS redirect
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: tc
spec:
  redirectScheme:
    scheme: https
    port: "{{ .Values.ingress.tlsPort }}"
    permanent: true
---

# Broadcasting
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregex-bs
  namespace: tc
spec:
  stripPrefix:
    prefixes:
      - "/bs/public"
---

# Frontend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregex-fe
  namespace: tc
spec:
  redirectRegex:
    regex: ^http(s?)://www\.(.*)
    replacement: http${1}://${2}
---

# File Server
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregex-fs
  namespace: tc
spec:
  stripPrefix:
    prefixes:
      - "/fs"
---

# Backend
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripregex-be
  namespace: tc
spec:
  stripPrefix:
    prefixes:
      - "/api"
---
