# Compose file for development of cypress-tests.
version: '3.9'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: testcenter_db
  MYSQL_USER: testcenter_user
  MYSQL_PASSWORD: testcenter_pw

services:
  traefik-system-test:
    container_name: testcenter-system-test-traefik
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - testcenter-system-test

  testcenter-system-test-db:
    container_name: testcenter-system-test-db
    image: iqbberlin/testcenter-db:current
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: testcenter_root_pw
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    user: root
    command:
      - --log_error_verbosity=1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 1s
      retries: 120
    volumes:
      - ../scripts/database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ../scripts/database/000-create-test-db.sh:/docker-entrypoint-initdb.d/000-create-test-db.sh
    ports:
      - "9091:3306"
      - "22:22"
    networks:
      - testcenter-system-test

  testcenter-system-test-backend:
    container_name: testcenter-system-test-backend
    image: iqbberlin/testcenter-backend:current
    environment:
      <<: *env-mysql
      MYSQL_HOST: testcenter-system-test-db
      MYSQL_PORT: 3306
      PASSWORD_SALT: t
      CACHE_SERVICE_INCLUDE_FILES: ${CACHE_SERVICE_INCLUDE_FILES:-off}
      CACHE_SERVICE_RAM: ${CACHE_SERVICE_RAM}
    volumes:
      - ../backend/.htaccess:/var/www/backend/.htaccess
      - ../backend/index.php:/var/www/backend/index.php
      - ../backend/initialize.php:/var/www/backend/initialize.php
      - ../backend/routes.php:/var/www/backend/routes.php
      - ../backend/src:/var/www/backend/src
      - ../backend/test:/var/www/backend/test
      - ../scripts/database:/var/www/database
      - ../definitions:/var/www/definitions
      - ../docs/dist:/docs/dist
      - ../package.json:/var/www/package.json
      - ../sampledata:/var/www/sampledata
      - ../backend/config/no-cors.htaccess/:/var/www/.htaccess
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
    ports:
      - 9005:9003 #xdebug
    networks:
      - testcenter-system-test
    depends_on:
      testcenter-system-test-db:
        condition: service_healthy

  testcenter-system-test-frontend:
    container_name: testcenter-system-test-frontend
    image: iqbberlin/testcenter-frontend:current
    build:
      context: ..
      dockerfile: frontend/docker/Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)"
    volumes:
      - ../frontend/src:/app/src
      - ../common:/common
    networks:
      - testcenter-system-test
    depends_on:
      - testcenter-system-test-backend
      - testcenter-system-test-db

  testcenter-system-test-broadcasting-service:
    container_name: testcenter-system-test-broadcasting-service
    image: iqbberlin/testcenter-broadcasting-service:current
    build:
      context: ..
      dockerfile: frontend/docker/Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/bs/public`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"
    volumes:
      - ../broadcasting-service/nest-cli.json:/app/nest-cli.json
      - ../broadcasting-service/package.json:/app/package.json
      - ../broadcasting-service/src:/app/src
      - ../broadcasting-service/tsconfig.json:/app/tsconfig.json
      - ../broadcasting-service/tsconfig.spec.json:/app/tsconfig.spec.json
      - ../common:/common
    networks:
      - testcenter-system-test

networks:
  testcenter-system-test:
    name: testcenter-system-test
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_DAEMON_MTU:-1500}
