# Compose file for development of cypress-tests.
version: '3.7'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: testcenter_db
  MYSQL_USER: testcenter_user
  MYSQL_PASSWORD: testcenter_pw

services:
  traefik-system-test:
    container_name: testcenter-system-test-traefik
    image: traefik:v2.2
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - testcenter-system-test

  testcenter-system-test-db:
    container_name: testcenter-system-test-db
    image: mysql:5.7
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: testcenter_root_pw
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    user: root
    command:
      - --log_error_verbosity=1
    volumes:
      - ../scripts/database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "9091:3306"
      - "22:22"
    networks:
      - testcenter-system-test

  testcenter-system-test-backend:
    container_name: testcenter-system-test-backend
    image: iqbberlin/testcenter-backend:current
    environment:
      <<: *env-mysql
      MYSQL_HOST: testcenter-system-test-db
      MYSQL_PORT: 3306
      TESTMODE_REAL_DATA: ${TESTMODE_REAL_DATA-false}
      SUPERUSER_NAME: super
      SUPERUSER_PASSWORD: user123
      WORKSPACE_NAME: example_workspace
    volumes:
      - ../backend/.htaccess:/var/www/backend/.htaccess
      - ../backend/autoload.php:/var/www/backend/autoload.php
      - ../backend/index.php:/var/www/backend/index.php
      - ../backend/initialize.php:/var/www/backend/initialize.php
      - ../backend/routes.php:/var/www/backend/routes.php
      - ../backend/src:/var/www/backend/src
      - ../backend/test:/var/www/backend/test
      - ../scripts/database:/var/www/database
      - ../definitions:/var/www/definitions
      - ../docs/dist:/docs/dist
      - ../package.json:/var/www/package.json
      - ../sampledata:/var/www/sampledata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
    networks:
      - testcenter-system-test
    depends_on:
      - testcenter-system-test-db

  testcenter-system-test-frontend:
    container_name: testcenter-system-test-frontend
    image: iqbberlin/testcenter-frontend:current
    build:
      context: ..
      dockerfile: frontend/docker/Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-frontend.rule=HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)"
    volumes:
      - ../docs/dist:/docs/dist
      - ../frontend/src:/app/src
    networks:
      - testcenter-system-test
    depends_on:
      - testcenter-system-test-backend
      - testcenter-system-test-db

  testcenter-system-test-broadcasting-service:
    container_name: testcenter-system-test-broadcasting-service
    image: iqbberlin/testcenter-broadcasting-service:current
    build:
      context: ..
      dockerfile: frontend/docker/Dockerfile
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/bs/public`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"
    volumes:
      - ../broadcasting-service/nest-cli.json:/app/nest-cli.json
      - ../broadcasting-service/package.json:/app/package.json
      - ../broadcasting-service/src:/app/src
      - ../broadcasting-service/tsconfig.json:/app/tsconfig.json
      - ../broadcasting-service/tsconfig.spec.json:/app/tsconfig.spec.json
      - ../common:/common
    networks:
      - testcenter-system-test

networks:
  testcenter-system-test:
    name: testcenter-system-test
