{{- if .Values.config.backend.fileServiceEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-file-server-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secret.fileServer.redisPassword | b64enc }}
{{- end }}
