# Compose-file for system-test
# Unfortunately we cannot inherit from the base compose file, because docker compose merges arrays such as volumes and networks
# a) it has to run in a different network
# b) we definitely don't want to include the anonymous volumes for data and db from dev here
# TODO move traefik-stuff from docker-compose.yml to separate file, so we can inherit from that instead of having a copy here

version: '3.9'

x-env-mysql: &env-mysql
  MYSQL_DATABASE: testcenter_db
  MYSQL_USER: testcenter_user
  MYSQL_PASSWORD: testcenter_pw

services:
  traefik-system-test:
    container_name: testcenter-system-test-traefik
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - testcenter-system-test

  testcenter-system-test-db:
    image: mysql:8.0
    container_name: testcenter-system-test-db
    environment:
      <<: *env-mysql
      MYSQL_ROOT_PASSWORD: testcenter_root_pw
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    user: root
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command:
      - --log_error_verbosity=1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 1s
      retries: 60
    ports:
      - "9091:3306"
      - "22:22"
    networks:
      - testcenter-system-test

  testcenter-system-test-backend:
    container_name: testcenter-system-test-backend
    environment:
      <<: *env-mysql
      MYSQL_HOST: testcenter-system-test-db
      MYSQL_PORT: 3306
      TESTMODE_REAL_DATA: ${TESTMODE_REAL_DATA-false}
      SUPERUSER_NAME: super
      SUPERUSER_PASSWORD: user123
      WORKSPACE_NAME: example_workspace
    image: iqbberlin/testcenter-backend:current
    volumes:
      - ./backend/.htaccess:/var/www/backend/.htaccess
      - ./backend/autoload.php:/var/www/backend/autoload.php
      - ./backend/index.php:/var/www/backend/index.php
      - ./backend/initialize.php:/var/www/backend/initialize.php
      - ./backend/routes.php:/var/www/backend/routes.php
      - ./backend/src:/var/www/backend/src
      - ./backend/test:/var/www/backend/test
      - ./database:/var/www/database
      - ./definitions:/var/www/definitions
      - ./docs/dist:/docs/dist
      - ./package.json:/var/www/package.json
      - ./sampledata:/var/www/sampledata
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - testcenter-system-test
    depends_on:
      testcenter-system-test-db:
        condition: service_healthy

  testcenter-system-test-frontend:
    container_name: testcenter-system-test-frontend
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
      target: dev
      args:
        HOST_UID: ${UID}
    environment:
      TERM: xterm
      TESTMODE_REAL_DATA: "yes" # TODO isn't this for backend only?
      CYPRESS_CACHE_FOLDER: /opt/cypress/cache
      CYPRESS_TC_TESTMODE: cli # cypress has to know this before setupNodeEvents
      TC_FRONTEND_RUN_COMMAND: "npx ng run testcenter-frontend:system-test-headless"
    image: iqbberlin/testcenter-frontend:current
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-backend.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.testcenter-backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.testcenter-backend.middlewares=testcenter-backend-stripprefix"
    volumes:
      - ./common:/common
      - ./definitions:/definitions
      - ./docs/dist:/docs/dist
      - ./frontend/.browserslistrc:/app/.browserslistrc
      - ./frontend/angular.json:/app/angular.json
      - ./frontend/cypress.config.js:/app/cypress.config.js
      - ./frontend/cypress:/app/cypress
      - ./frontend/docker/entrypoint.sh:/entrypoint.sh
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
    networks:
      - testcenter-system-test
    depends_on:
      - testcenter-system-test-backend
      - testcenter-system-test-db

  testcenter-system-test-broadcasting-service:
    container_name: testcenter-system-test-broadcasting-service
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
      target: dev
      args:
        HOST_UID: ${UID}
    image: iqbberlin/testcenter-broadcasting-service:current
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testcenter-broadcasting-service.rule=(HostRegexp(`{[a-z]*}.${HOSTNAME}`) || Host(`${HOSTNAME}`)) && PathPrefix(`/bs/public`)"
      - "traefik.http.middlewares.testcenter-broadcasting-service-stripprefix.stripprefix.prefixes=/bs"
      - "traefik.http.routers.testcenter-broadcasting-service.middlewares=testcenter-broadcasting-service-stripprefix"
    volumes:
      - ./broadcasting-service/docker/nest-cli.json:/app/nest-cli.json
      - ./broadcasting-service/package.json:/app/package.json
      - ./broadcasting-service/src:/app/src
      - ./broadcasting-service/tsconfig.build.json:/app/tsconfig.build.json
      - ./broadcasting-service/tsconfig.json:/app/tsconfig.json
      - ./common:/common
    networks:
      - testcenter-system-test

networks:
  testcenter-system-test:
    name: testcenter-system-test
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: $DOCKER_DAEMON_MTU
